### ISSUE TITLE
Problems ! Command & a nil value

### ISSUE THREAD

**Issue by Ruok-Capsule** [iThorgrim/lua-parangon#2]
Hey guys,

`AzerothCore rev. 556d91a2ea8d+ 2021-08-19 00:20:07 +0200 (master branch) (Unix, Release, Static) (worldserver-daemon) ready...
Eluna :: Parangon System start
`

today i've updated all my services .. core , mods also parangon.
but now parangon does not work . Maybe i can get help !

Table `command` have non-existing command 'parangon', skip.
lua_scripts/lua-parangon.lua:301: attempt to call method 'GossipSetText' (a nil value)

Thanks

**Comment by iThorgrim** [comment]
You need to add : https://github.com/iThorgrim/lua-parangon/blob/master/GossipTextExtension.lua in your lua_scripts folder

**Comment by Ruok-Capsule** [comment]
Sorry ...... =(

all is fine i've forget to add this file ....

thanks for fast support
